## Ejercicio 1

En la celda de código siguiente crea un dataframe llamado frutas que tenga esta estructura: 
<br><br>
<img src="imgs/ej-01.PNG">

In [3]:
import pandas as pd

frutas = pd.DataFrame({'Manzanas': [30], 'Plátanos': [21]})
display(frutas)

   Manzanas  Plátanos
0        30        21

## Ejercicio 2

Crea un dataframe llamado ventas_frutas que encaje con la siguiente foto:

<br>

<img src="imgs/ej-01.2.PNG">

In [6]:
ventas_frutas = pd.DataFrame({'Manzanas': [35, 41], 'Plátanos': [21, 34]},
                             index=['Ventas 2017', 'Ventas 2018'])
display(ventas_frutas)

             Manzanas  Plátanos
Ventas 2017        35        21
Ventas 2018        41        34

## Ejercicio 3

Crea una variable ingredientes que sea una serie con este contenido:

<img src="imgs/ej-01.3.PNG">

In [10]:
ingredientes = pd.Series(['4 tazas', '1 taza', '2 unidades XL', '1 pieza'], 
                         index=['Harina', 'Leche', 'Huevos', 'Limón'],
                         name='Cena',
                         dtype=object)
display(ingredientes)

Harina          4 tazas
Leche            1 taza
Huevos    2 unidades XL
Limón           1 pieza
Name: Cena, dtype: object

## Ejercicio 4

Lee el dataset llamado **datos_casas_india.csv** que está en la ruta **datasets/datos_casas_india.csv** en una variable de tipo dataframe y llámalo casas_india, finalmente muestra su contenido.

In [12]:
casas_india = pd.read_csv('../datasets/datos_casas_india.csv')
casas_india

,house_type,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
0,1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1,1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
2,2 BHK Independent Floor,500 sq ft,Uttam Nagar,Delhi,28.618677,77.053352,8500,INR,1.0,NaN,NaN,NaN,Posted 12 days ago,"Zero Brokerage.\n\n2 Room set, Govt bijali Met...",No Deposit,Semi-Furnished
3,3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
4,2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4 BHK Villa,"5,896 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1022001,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its four bhk villa in the super location of De...,"40,10,102",Unfurnished
4996,5 BHK Independent House,"6,521 sq ft",Sunder Nagar,Delhi,28.618437,76.961784,1549181,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,A 5 bhk property is available for rent in Sund...,"54,01,015",Unfurnished
4997,3 BHK Independent Floor,"1,855 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"18,18,181",Unfurnished
4998,3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301011,INR,3.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,110",Unfurnished
4999,3 BHK Independent Floor,"2,856 sq ft",New Friends Colony,Delhi,28.567051,77.273560,301012,INR,4.0,2.0,NaN,NaN,Posted 2 months ago,Its three bhk builder floor in the super locat...,"10,10,182",Unfurnished

## Ejercicio 5

Ejecuta la siguiente celda para crear un dataframe llamado animales y crea una celda extra en la que se escriba ese dataframe en un fichero CSV en la ruta **datasets/animales.csv**

In [16]:
animales = pd.DataFrame({'Vacas': [15, 25], 'Cabras': [25, 20]},
                        index=['año 1', 'año 2'])
display(animales)

       Vacas  Cabras
año 1     15      25
año 2     25      20

In [17]:
animales.to_csv('../datasets/animales.csv')